export { Mailgent } from "./client"
export { MailgentPlatform } from "./platform"
export { MailgentApiError } from "./errors"
export type {
  MailgentConfig,
  PlatformConfig,
  MessageResponse,
  ThreadResponse,
  ThreadDetailResponse,
  VaultCredentialType,
  ApiKeySecretData,
  ApiKeyClientPairData,
  CardData,
  CardMetadata,
  ShippingAddressData,
  CredentialMetadata,
  CredentialWithData,
  IdentityPurpose,
  IdentityResponse,

  IdentitySummary,
  IdentityDetail,
  CreateIdentityParams,
  CreateIdentityResponse,
  UpdateIdentityParams,
  RotateKeyResponse,
  PaginatedIdentities,
  CalendarEvent,
  CreateCalendarEventParams,
  UpdateCalendarEventParams,
  PaginatedCalendarEvents,
  ActivityLog,
  LogsStatsResponse,
  TotpResponse,
  PaginatedMessages,
  PaginatedThreads,
  PaginatedLogs,
  VaultList,
  PaymentStatus,
  PaymentEndpointSummary,
  PaymentSummary,
  PaymentReceiptBody,
  PaymentReceipt,
  PaymentDetail,
  PaginatedPayments,
  PaymentErrorCode,
  PaymentError,
  PaymentsPayParams,
  PaymentsPaySuccess,
  PaymentsPayFailure,
  PaymentsPayResponse,
  PaymentActivityIn,
  PaymentActivityOut,
  PaymentActivityRow,
  PaymentActivityList,
  Mandate,
  MandateCreateParams,
  MandateList,
  SlackConnection,
  SlackConnectResponse,
  SlackChannel,
  SlackChannelList,
  SendSlackMessageParams,
  SlackMessageSent,
  SlackMessage,
  SlackMessageList,
  SocialAccount,
  SocialAccountList,
  CreateSocialPostParams,
  CreateSocialPostResponse,
  SocialPostSummary,
  SocialPostList,
  SocialPostDetail,
} from "./types"
export { PAYMENT_ERROR_CODES } from "./types"
export type { DidDocument } from "./resources/did"
